### ISSUE TITLE
Creating Flags in Main Screen 

### ISSUE THREAD

**Issue by daphliu-zz** [ubclaunchpad/soil-topARgraphy#45]
res > drawable > ic_flag

**Comment by daphliu-zz** [comment]
Pressing the + button creates flag in center of screen 
Currently use the dummy ImageViewer Sarah made 
Uses the res > drawable > ic_flag.xml

**Comment by SophieMBerger** [comment]
I just wanted to complete this ticket, however, the ic_flag.xml throws this error: "attribute android:fillcolor is not allowed here". It does the same with height and width. Could this be because the xmlns URI is missing?

**Comment by daphliu-zz** [comment]
hmm I would need more context! What branch are you on?

**Comment by SophieMBerger** [comment]
I'm on the branch addFlag
