### ISSUE TITLE
Add rest of toolbar options as well as terrain image to main view

### ISSUE THREAD

**Issue by sarahdagger** [ubclaunchpad/soil-topARgraphy#47]
- Make sure terrain objects are defined properly
- Add a dummy terrain to TerrainInRecyclerView fragment
- When terrain is clicked, load main view with terrain image
- Add back button (to TerrainInRecyclerView) functionality
- Add export to JSON button functionality

**Comment by daphliu-zz** [comment]
export to JSON button functionality - DONE 

good job on the notes :)
