### ISSUE TITLE
Import Map 

### ISSUE THREAD

**Issue by daphliu-zz** [ubclaunchpad/soil-topARgraphy#60]
Import map into the app with coordinates (50.753836, -120.404478)

**Comment by daphliu-zz** [comment]
https://developers.google.com/maps/documentation/android-sdk/utility/geojson

**Comment by SophieMBerger** [comment]
@daphliu I just wanted to let you know that I don't know whether the initial position of the map, when the screen loads, is too zoomed in or out. I can however easily change that, so just let me know!

**Comment by SophieMBerger** [comment]
@daphliu  Also, I can change the style of the map, so let me know if I should do that (eg. satellite).

**Comment by daphliu-zz** [comment]
It would be easy for review if you include the screenshot of the map!

**Comment by SophieMBerger** [comment]
![screenshot_1550339340](https://user-images.githubusercontent.com/28648975/52903393-b8364100-31d1-11e9-85f8-e5da83798aa6.png)

**Comment by daphliu-zz** [comment]
PROGRESS
- map loads 

TODO: 
- play with zoom levels
